export const MPESA_LIST_REQUEST = 'MPESA_LIST_REQUEST';
export const MPESA_LIST_SUCCESS = 'MPESA_LIST_SUCCESS';
export const MPESA_LIST_FAIL = 'MPESA_LIST_FAIL';

export const MPESA_DETAILS_REQUEST = 'MPESA_DETAILS_REQUEST';
export const MPESA_DETAILS_SUCCESS = 'MPESA_DETAILS_SUCCESS';
export const MPESA_DETAILS_FAIL = 'MPESA_DETAILS_FAIL';

export const MPESA_CREATE_REQUEST = 'MPESA_CREATE_REQUEST';
export const MPESA_CREATE_SUCCESS = 'MPESA_CREATE_SUCCESS';
export const MPESA_CREATE_FAIL = 'MPESA_CREATE_FAIL';
export const MPESA_CREATE_RESET = 'MPESA_CREATE_RESET';

export const MPESA_UPDATE_REQUEST = 'MPESA_UPDATE_REQUEST';
export const MPESA_UPDATE_SUCCESS = 'MPESA_UPDATE_SUCCESS';
export const MPESA_UPDATE_FAIL = 'MPESA_UPDATE_FAIL';
export const MPESA_UPDATE_RESET = 'MPESA_UPDATE_RESET';

export const MPESA_DELETE_REQUEST = 'MPESA_DELETE_REQUEST';
export const MPESA_DELETE_SUCCESS = 'MPESA_DELETE_SUCCESS';
export const MPESA_DELETE_FAIL = 'MPESA_DELETE_FAIL';
