


export const USER_WISHES_REQUEST = 'USER_WISHES_REQUEST'
export const USER_WISHES_SUCCESS = 'USER_WISHES_SUCCESS'
export const USER_WISHES_FAIL = 'USER_WISHES_FAIL'
export const USER_WISHES_RESET = 'USER_DETAILS_RESET'

export const WISH_ADD_ITEM = 'WISH_ADD_ITEM'
export const WISH_CLEAR_ITEMS = 'WISH_RESET'
export const WISH_REMOVE_ITEM = 'WISH_REMOVE_ITEM'